"""Fill every (locale, class) cell of the intent training set through `intent_gen` (D19, D20).

A cell is 10 families, each a seed plus 2 paraphrases, so 30 live items (the
check accepts 29 or more accepted). Everything is generated by `gpt-6-luna` and
audited by a human afterwards (`accepted` starts as null). Rejected items stay
in the file with `accepted: false` and are regenerated until the cell holds 30
live items.

Usage: `uv run --project backend python -m ml.intent.generate [--locale L]
[--class C] [--data-dir D] [--plan]`. `--plan` prints the calls it would make
and makes none.

`--retire-slots S1,S2 --retire-generator-version N` retires (`accepted: false`)
every item of those slots stamped `@vN`, changes nothing else and makes no LLM
call. The next run regenerates the retired families through the top-up logic.

`--card-type-topup [--card-type-families K]` (T41) appends K families (default
2, half credit and half debit, prompt `intent_gen@v3`, slot `card_type`) to
every in-scope intent cell (not the scope classes nor greeting, thanks_close,
affirm, deny), one call per cell. Existing
items are never changed or reordered. A cell that already holds K live
`card_type` families is skipped, so the mode is re-runnable. `--plan` works
with it.
"""

import argparse
import asyncio
import re
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Literal

from pydantic import BaseModel

from ml.intent.data_io import LOCALES, SLOT_MIX, DataFile, DataItem, load_files, write_file

if TYPE_CHECKING:
    from app.core.llm import LLMClient

__all__ = ["main", "plan_cell"]

# `app.*` is imported inside functions: `data_io` puts `backend/` on `sys.path`
# as a side effect, and ruff's import sorting would otherwise run `app` first.
_PROMPT_NAME, _PROMPT_VERSION = "intent_gen", 2
_CARD_TYPE_PROMPT_VERSION = 3
_PROMPTS_DIR = Path(__file__).resolve().parent / "prompts"
_CARD_TYPE_SLOT = "card_type"
_CARD_TYPES = ("credit", "debit")  # alternated, so K families are half and half
_DEFAULT_CARD_TYPE_FAMILIES = 2
# Naming a card type in these turns is unnatural and would teach the wrong thing (T41).
_CARD_TYPE_EXCLUDED = frozenset({"greeting", "thanks_close", "affirm", "deny"})
_DEFAULT_DATA_DIR = Path(__file__).resolve().parent / "data"
_FAMILIES = 10
_PER_FAMILY = 3
_CELL_SIZE = _FAMILIES * _PER_FAMILY
# Variety slot by family index (1-based -> index 0..9), in SLOT_MIX order (D19).
_SLOTS = [slot for slot, n in SLOT_MIX.items() for _ in range(n)]

_DIGIT_RUN = re.compile(r"\d{13,}")
_EMAIL = re.compile(r"[\w.+-]+@[\w-]+\.[A-Za-z]{2,}")

# What each class means, for the prompt's "Class description" line.
_DESCRIPTIONS = {
    "card_status": "the customer asks whether their card is active, blocked or in what state it is",
    "balance_due": "the customer asks how much they owe, the statement balance or the due date",
    "decline_explain": "the customer asks why a purchase or payment with the card was declined",
    "transaction_search": "the customer wants to look up or list past purchases or charges",
    "pending_reversal_explain": "a pending charge or a reversal that has not shown up yet",
    "card_block": "the customer wants to block or lock their card (lost, stolen, temporary lock)",
    "card_unlock": "the customer wants to unlock a card that was temporarily locked",
    "unrecognized_charge": "the customer reports a charge they do not recognize",
    "replacement_request": "the customer wants a replacement card (damaged, lost, stolen)",
    "human_request": "the customer asks to talk to a human agent",
    "general_question": "a general question about cards or the service, not tied to one action",
    "greeting": "a greeting that opens the conversation",
    "thanks_close": "thanks or a goodbye that closes the conversation",
    "affirm": "a short yes or agreement as an answer to the assistant",
    "deny": "a short no or refusal as an answer to the assistant",
    "pix_boleto": "the customer asks about Pix or boleto payments (a product not served here)",
    "loans": "the customer asks about loans or credit lines, not a card topic",
    "accounts": "the customer asks about bank accounts (opening, closing, checking account)",
    "investments": "the customer asks about investments or savings products",
    "insurance": "the customer asks about insurance products",
    "transfers": "the customer asks about bank transfers between accounts",
    "other": "a request that has nothing to do with card support",
}


class _Family(BaseModel):
    slot: str
    seed: str
    paraphrases: list[str]


class _CellReply(BaseModel):
    families: list[_Family]


def _generator(version: int = _PROMPT_VERSION) -> str:
    from app.core.llm.registry import MODEL_REGISTRY

    return f"{MODEL_REGISTRY['intent_gen']['openai']}:{_PROMPT_NAME}@v{version}"


def _labels() -> tuple[str, ...]:
    from app.domains.conversation.intent_registry import classifier_labels

    return classifier_labels()


def _family_id(cls: str, locale: str, index: int) -> str:
    return f"{cls}-{locale}-{index:02d}"


def _family_index(family: str) -> int:
    return int(family.rsplit("-", 1)[1])


def _is_live(item: DataItem) -> bool:
    return item.accepted is not False


def _hygiene_ok(text: str) -> bool:
    """R5 hygiene: no raw 13+ digit run (card number shape), no email."""
    return not (_DIGIT_RUN.search(text) or _EMAIL.search(text))


def plan_cell(file: DataFile | None) -> tuple[list[int], list[int]]:
    """(missing family indices, family indices with a rejected or dropped item).

    A family that has no item at all is missing (it comes from the one cell
    call). A family with fewer than 3 live items needs a per-family call that
    regenerates only those items. A cell already holding 30 live items needs
    nothing.
    """
    items = file.items if file else []
    if sum(1 for i in items if _is_live(i)) >= _CELL_SIZE:
        return [], []
    present: dict[int, list[DataItem]] = {}
    for item in items:
        present.setdefault(_family_index(item.family), []).append(item)
    missing = [n for n in range(1, _FAMILIES + 1) if n not in present]
    regen = [
        n for n, fam in sorted(present.items()) if sum(1 for i in fam if _is_live(i)) < _PER_FAMILY
    ]
    return missing, regen


def _calls(missing: list[int], regen: list[int]) -> int:
    return (1 if missing else 0) + len(regen)


def _slot_name(index: int) -> str:
    return _SLOTS[index - 1]


def _system(locale: str, cls: str, slots: list[str]) -> str:
    # str.replace, not format: the prompt's JSON example holds literal braces.
    text = (_PROMPTS_DIR / f"{_PROMPT_NAME}@v{_PROMPT_VERSION}.md").read_text(encoding="utf-8")
    values = {
        "{locale}": locale,
        "{class_name}": cls,
        "{class_description}": _DESCRIPTIONS[cls],
        "{slots}": ", ".join(slots),
    }
    for key, value in values.items():
        text = text.replace(key, value)
    return text


async def _ask(llm: "LLMClient", locale: str, cls: str, slots: list[str]) -> list[_Family]:
    from app.core.llm import PromptRef

    reply = await llm.structured(
        step="intent_gen",
        prompt=PromptRef(_PROMPT_NAME, _PROMPT_VERSION),
        system=_system(locale, cls, slots),
        user="Generate the cell now.",
        schema=_CellReply,
    )
    return reply.families


def _new_item(
    cls: str,
    locale: str,
    kind: str | None,
    index: int,
    origin: Literal["seed", "paraphrase"],
    text: str,
) -> DataItem:
    scope = kind is not None
    return DataItem(
        text=text.strip(),
        intents=[] if scope else [cls],
        status=kind if scope else "clear",  # type: ignore[arg-type]
        topic=cls if scope else None,
        family=_family_id(cls, locale, index),
        slot=_slot_name(index),  # type: ignore[arg-type]
        origin=origin,
        generator=_generator(),
        accepted=None,
    )


def _candidates(family: _Family) -> list[tuple[Literal["seed", "paraphrase"], str]]:
    out: list[tuple[Literal["seed", "paraphrase"], str]] = [("seed", family.seed)]
    out += [("paraphrase", p) for p in family.paraphrases[:2]]
    return out


async def fill_cell(
    llm: "LLMClient", locale: str, cls: str, file: DataFile | None, kind: str | None
) -> DataFile:
    """Return the cell's file with the missing items generated (accepted: null)."""
    if file is None:
        file = DataFile(
            provenance="ai-generated-human-audited",
            version=1,
            locale=locale,
            class_=cls,
            items=[],  # type: ignore[arg-type]
        )
    missing, regen = plan_cell(file)
    seen = {i.text.strip().casefold() for i in file.items}

    def add(index: int, origin: Literal["seed", "paraphrase"], text: str) -> None:
        key = text.strip().casefold()
        if not text.strip() or key in seen or not _hygiene_ok(text):
            return
        seen.add(key)
        file.items.append(_new_item(cls, locale, kind, index, origin, text))

    if missing:
        families = await _ask(llm, locale, cls, _SLOTS)
        for index in missing:
            if index <= len(families):
                for origin, text in _candidates(families[index - 1]):
                    add(index, origin, text)

    for index in regen:
        live = [i for i in file.items if _family_index(i.family) == index and _is_live(i)]
        have_seed = any(i.origin == "seed" for i in live)
        have_para = sum(1 for i in live if i.origin == "paraphrase")
        # One call per family: the prompt wants 10 same-slot families, the first is used.
        families = await _ask(llm, locale, cls, [_slot_name(index)] * _FAMILIES)
        if not families:
            continue
        for origin, text in _candidates(families[0]):
            if origin == "seed" and not have_seed:
                add(index, origin, text)
                have_seed = True
            elif origin == "paraphrase" and have_para < 2:
                before = len(file.items)
                add(index, origin, text)
                have_para += len(file.items) - before

    file.items.sort(key=lambda i: (_family_index(i.family), i.origin != "seed"))
    return file


def card_type_plan(file: DataFile | None, families: int) -> int:
    """How many `card_type` families a cell still needs (0 = skip).

    A family counts when it holds at least one non-rejected item, so a re-run
    after a partial or interrupted run only asks for the missing ones.
    """
    if file is None:
        return 0
    have = {i.family for i in file.items if i.slot == _CARD_TYPE_SLOT and _is_live(i)}
    return max(0, families - len(have))


async def topup_card_type(
    llm: "LLMClient", locale: str, cls: str, file: DataFile, kind: str | None, need: int
) -> DataFile:
    """Append `need` card_type families (one call). Existing items are left as they are."""
    from app.core.llm import PromptRef

    have = len({i.family for i in file.items if i.slot == _CARD_TYPE_SLOT and _is_live(i)})
    types = [_CARD_TYPES[(have + n) % len(_CARD_TYPES)] for n in range(need)]
    text = (_PROMPTS_DIR / f"{_PROMPT_NAME}@v{_CARD_TYPE_PROMPT_VERSION}.md").read_text("utf-8")
    values = {
        "{locale}": locale,
        "{class_name}": cls,
        "{class_description}": _DESCRIPTIONS[cls],
        "{count}": str(need),
        "{items}": str(need * _PER_FAMILY),
        "{card_types}": ", ".join(types),
    }
    for key, value in values.items():
        text = text.replace(key, value)
    reply = await llm.structured(
        step="intent_gen",
        prompt=PromptRef(_PROMPT_NAME, _CARD_TYPE_PROMPT_VERSION),
        system=text,
        user="Generate the families now.",
        schema=_CellReply,
    )
    # Ids never reuse a rejected card_type family's number: next free index of the file.
    index = max((_family_index(i.family) for i in file.items), default=0)
    seen = {i.text.strip().casefold() for i in file.items}
    scope = kind is not None
    for family in reply.families[:need]:
        index += 1
        for origin, text_ in _candidates(family):
            key = text_.strip().casefold()
            if not text_.strip() or key in seen or not _hygiene_ok(text_):
                continue
            seen.add(key)
            file.items.append(
                DataItem(
                    text=text_.strip(),
                    intents=[] if scope else [cls],
                    status=kind if scope else "clear",  # type: ignore[arg-type]
                    topic=cls if scope else None,
                    family=_family_id(cls, locale, index),
                    slot=_CARD_TYPE_SLOT,  # type: ignore[arg-type]
                    origin=origin,
                    generator=_generator(_CARD_TYPE_PROMPT_VERSION),
                    accepted=None,
                )
            )
    return file


def _scope_kinds() -> dict[str, str]:
    from app.domains.policy.registry import get_policies

    return {topic: t.kind for topic, t in get_policies().scope.topics.items()}


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--locale", choices=LOCALES)
    parser.add_argument("--class", dest="cls", choices=_labels())
    parser.add_argument("--data-dir", type=Path, default=_DEFAULT_DATA_DIR)
    parser.add_argument("--plan", action="store_true", help="print the calls, make none")
    parser.add_argument(
        "--card-type-topup",
        action="store_true",
        help="append card_type families (prompt v3) to every in-scope intent cell",
    )
    parser.add_argument(
        "--card-type-families", type=int, default=_DEFAULT_CARD_TYPE_FAMILIES, help="K per cell"
    )
    parser.add_argument("--retire-slots", help="comma-separated slots whose old items are retired")
    parser.add_argument("--retire-generator-version", type=int, help="prompt version to retire")
    return parser.parse_args(argv)


def _retire(args: argparse.Namespace) -> int:
    """Set `accepted: false` on old-version items of the given slots. No LLM call."""
    slots = {s.strip() for s in args.retire_slots.split(",") if s.strip()}
    suffix = f"@v{args.retire_generator_version}"
    total = 0
    for file in load_files(args.data_dir):
        if args.locale and file.locale != args.locale:
            continue
        if args.cls and file.class_ != args.cls:
            continue
        hit = [
            i
            for i in file.items
            if i.slot in slots and i.generator.endswith(suffix) and i.accepted is not False
        ]
        if not hit:
            continue
        for item in hit:
            item.accepted = False
        write_file(args.data_dir / file.locale / f"{file.class_}.yaml", file)
        print(f"{file.locale} {file.class_}: retired {len(hit)}")
        total += len(hit)
    print(f"retired {total} item(s)")
    return 0


async def _run(args: argparse.Namespace) -> int:
    if args.retire_slots:
        if args.retire_generator_version is None:
            raise SystemExit("--retire-slots needs --retire-generator-version")
        return _retire(args)
    kinds = _scope_kinds()
    existing = {(f.locale, f.class_): f for f in load_files(args.data_dir)}
    locales = [args.locale] if args.locale else list(LOCALES)
    classes = [args.cls] if args.cls else list(_labels())
    llm = None
    if not args.plan:
        from app.core.llm import get_llm_client

        llm = get_llm_client()
    cells = calls = 0
    for locale in locales:
        for cls in classes:
            file = existing.get((locale, cls))
            if args.card_type_topup:
                if cls in kinds or cls in _CARD_TYPE_EXCLUDED:  # scope + conversational classes
                    continue
                cells += 1
                need = card_type_plan(file, args.card_type_families)
                calls += 1 if need else 0
                if args.plan:
                    print(f"{locale} {cls}: {1 if need else 0} call(s) (card_type families {need})")
                elif need and llm is not None and file is not None:
                    done = await topup_card_type(llm, locale, cls, file, None, need)
                    write_file(args.data_dir / locale / f"{cls}.yaml", done)
                continue
            cells += 1
            missing, regen = plan_cell(file)
            n = _calls(missing, regen)
            calls += n
            if args.plan:
                print(f"{locale} {cls}: {n} call(s) (new {len(missing)}, regen {len(regen)})")
                continue
            if n == 0 or llm is None:
                continue
            done = await fill_cell(llm, locale, cls, file, kinds.get(cls))
            write_file(args.data_dir / locale / f"{cls}.yaml", done)
    verb = "would make" if args.plan else "made"
    print(f"{cells} cells, {verb} {calls} call(s)")
    return 0


def main(argv: list[str] | None = None) -> int:
    return asyncio.run(_run(_parse_args(argv)))


if __name__ == "__main__":
    sys.exit(main())
