"""B3: the compiled graph and its diagram, plus the Q3 `RESET_FACTS` proof.

See D8/D9 and the spec's Test list row `test_graph.py`. This is the file's
only test: it also carries the orchestrator's mid-card addendum (T9 review)
that a two-turn run on one thread, through the real `MemorySaver`
checkpointer, must show turn 2's `facts` holding only turn 2's facts -- the
one way to know the `_FactsReset` marker (`state.py`) survives LangGraph's
write path rather than merely asserting it in isolation.
"""

import asyncio
from pathlib import Path
from uuid import uuid4

from langgraph.checkpoint.memory import MemorySaver

from app.domains.conversation.graph import build_graph, run_turn
from app.domains.conversation.nodes.compose import ComposeDraft
from app.domains.conversation.nodes.handoff_summary import HandoffSummaryDraft
from app.domains.conversation.schemas import NLUResult, NLUSlots
from app.domains.conversation.tools.context import ToolContext
from app.domains.conversation.tools.fakebank import FakeBank
from app.domains.conversation.tools.handoff import InMemoryHandoffTools
from tests.conftest import RecordingAudit, ScriptedLLM

_MMD_PATH = Path(__file__).resolve().parents[3] / "docs" / "diagrams" / "turn-graph-v0.mmd"
_D13_CREDIT_KEYS = {
    "card_mask",
    "card_kind",
    "status",
    "expiry",
    "credit_limit",
    "available_credit",
    "currency",
}


def test_graph_compiles_and_diagram_is_current(fakebank_dir: Path) -> None:
    graph = build_graph(MemorySaver())

    # B3: the committed diagram matches the compiled graph's own drawing. The
    # file is generated by `python -m … --mermaid > file` (a `print()`, hence
    # the one added trailing newline) and checked out as CRLF; both sides are
    # normalized before comparing.
    actual = graph.get_graph().draw_mermaid().replace("\r\n", "\n") + "\n"
    expected = _MMD_PATH.read_text(encoding="utf-8").replace("\r\n", "\n")
    assert actual == expected

    # Q3: `CLI-TFSINGLE0002` (T5) has exactly one eligible card, so both
    # turns resolve it directly (`Selected`, no clarification) and both route
    # to `card_info` -> `compose`.
    ctx = ToolContext(
        customer_id="CLI-TFSINGLE0002",
        conversation_id=uuid4(),
        actor="customer",
        policy_version="unversioned",
        trace_id="test-trace",
    )
    bank_tools = FakeBank(ctx, fakebank_dir)
    nlu_turn = NLUResult(language="es", intents=["card_status"], status="clear", slots=NLUSlots())
    draft = ComposeDraft(text="Tu tarjeta {card_mask} esta {status}.")
    llm = ScriptedLLM({"nlu": [nlu_turn, nlu_turn], "compose": [draft, draft]})
    config = {
        "configurable": {
            "thread_id": "t-graph-test",
            "session": ctx,
            "bank_tools": bank_tools,
            "llm": llm,
        }
    }

    reply1, debug1 = asyncio.run(
        run_turn(graph, "hola, cual es el estado de mi tarjeta?", config=config)
    )
    reply2, debug2 = asyncio.run(run_turn(graph, "y ahora?", config=config))

    assert debug1.route == "card_info"
    assert debug2.route == "card_info"
    assert reply1 == "Tu tarjeta •••• 2222 esta Activa."
    assert reply2 == reply1

    snapshot = asyncio.run(graph.aget_state(config))
    facts = snapshot.values["facts"]
    keys = [fact.key for fact in facts]
    # No duplicates: if `RESET_FACTS` had lost its subclass through the
    # checkpointer's write path, turn 2 would append onto turn 1's facts
    # instead of clearing them, and every D13 key would show up twice.
    assert len(keys) == len(set(keys)), f"facts accumulated across turns: {keys}"
    assert set(keys) == _D13_CREDIT_KEYS


def test_human_mode_relays_without_llm(fakebank_dir: Path) -> None:
    """A3: once a handoff put the conversation in human mode, the bot stops."""
    graph = build_graph(MemorySaver())
    ctx = ToolContext(
        customer_id="CLI-TFSINGLE0002",
        conversation_id=uuid4(),
        actor="customer",
        policy_version="unversioned",
        trace_id="test-trace",
    )
    tools = InMemoryHandoffTools()
    nlu_turn = NLUResult(language="es", intents=["human_request"], status="clear", slots=NLUSlots())
    llm = ScriptedLLM(
        {
            "nlu": [nlu_turn],
            "handoff_summary": [HandoffSummaryDraft(request="Pidió hablar con {queue_label}.")],
        }
    )
    config = {
        "configurable": {
            "thread_id": "t-human-mode",
            "session": ctx,
            "bank_tools": FakeBank(ctx, fakebank_dir),
            "llm": llm,
            "handoff_tools": tools,
            "audit": RecordingAudit(),
        }
    }

    asyncio.run(run_turn(graph, "quiero hablar con una persona", config=config))
    assert len(tools.created) == 1
    calls_after_handoff = len(llm.calls)

    reply, debug = asyncio.run(run_turn(graph, "hola? sigue alguien?", config=config))

    assert len(llm.calls) == calls_after_handoff
    assert reply == ""
    assert debug.route == "relay_to_agent"
    assert len(tools.created) == 1
